spring:
  application:
    name: routex

  kafka:
    bootstrap-servers: localhost:9092

    admin:
      fail-fast: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks : all
      retries : 2147483647


    consumer:
      group-id: routex-ride-request-logger
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.routex.dispatch,com.routex.matching

    listener:
      ack-mode: manual